### ISSUE TITLE
delete command threw an exception

### ISSUE THREAD

**Issue by spaghetti-** [CS2103AUG2016-W15-C1/TaskRuby#60]
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at models.Task.getTaskPriority(Task.java:124)
	at core.DeleteCommand.execute(DeleteCommand.java:30)
	at core.Parser.parse(Parser.java:70)
	at controllers.TaskController.parseInput(TaskController.java:49)
	at controllers.TaskController.lambda$6(TaskController.java:76)
```

**Comment by spaghetti-** [comment]
only happens for tasks without priority

**Comment by spaghetti-** [comment]
Fixed by addition to default priority levels to every task.
